### ISSUE TITLE
Link the host email-id with contact us form

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/discussion_forum_website#10]
On the contact form at contact.html, on send button link it with the host email-id to fetch the data
While coming to the host email-id list, you can contact me, I will provide the same.

**Comment by prichoms** [comment]
couldn't get that clearly

**Comment by siddharth25pandey** [comment]
@prichoms after writing in contact form, we have to fetch the data & collect it. So, for collecting the whole data we have to send it to a particular host email-id where every time we got mail if somebody write in contact form. The issue is to link the host email-id with the send button on contact us page.

**Comment by siddharth25pandey** [comment]
@prichoms if you want to work on this issue, do comment it, I will assign it to you!
Thanks!

**Comment by prichoms** [comment]
would love working on it
would take a bit of time coz this involves back-end processing
thnx in advance

**Comment by siddharth25pandey** [comment]
@prichoms  Assigned.
start working on it.
Best of Luck!
Thanks!

**Comment by siddharth25pandey** [comment]
@prichoms Link the host email id with MongoDB

**Comment by siddharth25pandey** [comment]
@prichoms Thanks for working but this issue is resolved.
Thanks!
