### ISSUE TITLE
Adding the logo image in webpages

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/discussion_forum_website#34]
Insert the logo.png in public folder in each of the webpages accurately.
The logo should be at top left corner & dimensionally precise.

**Comment by surya1701** [comment]
Sent pull request
Please assign and close issue

**Comment by siddharth25pandey** [comment]
@surya1701  not working correctly. Now only home page is opening.
I will suggest you to before sending any PR please the run the setup in your local machine

**Comment by siddharth25pandey** [comment]
Issue resolved
