### ISSUE TITLE
Balancing the background image

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/discussion_forum_website#36]
When you see the home, about , contact_us page's background and compare with login & register page's background you will notice that some brightness effect in backrground images is missing in home, about, contact_us page. So, please make same for all pages.(By changing the styling in CSS)
Default background image composition should be like login , register page.
You have to change the effect as same as above mentioned.
Thanks!

**Comment by surya1701** [comment]
So you want all pages to have background like the login/register page?

**Comment by surya1701** [comment]
Please assign

**Comment by siddharth25pandey** [comment]
@surya1701 Absolutely correct ! Same texture as login/register page.

**Comment by surya1701** [comment]
Has been merged

**Comment by siddharth25pandey** [comment]
Issue resolved
