### ISSUE TITLE
Creation of Home Page

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/discussion_forum_website#5]
Create a home page for our website which include home, about, register & Contact Us as top Navigation bar. Also link the present main_page.html to register Navigation bar

**Comment by Shreyashm16** [comment]
Assign this to me

**Comment by siddharth25pandey** [comment]
@Shreyashm16 Please rename the present main_page.html as register.html and do same for css & JS file. Also add the name of the home page that you are going to upload as main_page.html.
Also, add footer with same dimensions as in registration page to all the pages like home, about, contact us, etc.
Thanks!
