### ISSUE TITLE
User profile & Avtar

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/discussion_forum_website#6]
Creation of user profile & avtar in another html file is required where user profile will show and if due to any unavoidable circumstances profile is not available than avatar of user have to show.
After that link it to the original User server.

**Comment by surya1701** [comment]
Front-end

**Comment by siddharth25pandey** [comment]
@surya1701  After making the webpage please link it to the login button in sign in page in register.html
Thanks!
