### ISSUE TITLE
Styling the existing main_page file

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/discussion_forum_website#8]
Add some hover effect, some good color composition and font style to the existing registration page and login page. Styling is need with some textural animated behaviour

**Comment by piyush9311** [comment]
Sir,i want to work on this  issue

**Comment by ronitsingh1405** [comment]
Is this issue open? Can I work on this or have you assigned someone?

**Comment by siddharth25pandey** [comment]
@ronitsingh1405 it is already assigned. If you want to work on this, you can send PR for it but I will select the best one. Alternatively, you can work on the remaining existing issues.
Thanks!

**Comment by siddharth25pandey** [comment]
@piyush9311 Till what you have done is alright! but some modifications are required like please add the same background image for register page & also make the same styling for Contact form with same textures.
Thanks!

**Comment by siddharth25pandey** [comment]
@piyush9311 Instead of user id in label in register form, rename as name

**Comment by siddharth25pandey** [comment]
Closing this issue.
Work Completed.
